// Emit callable load instructions from the real decoder and translator.
#include "ps2recomp/code_generator.h"
#include "ps2recomp/instructions.h"
#include "ps2recomp/r5900_decoder.h"

#include <cstdint>
#include <cstdio>

using namespace ps2recomp;

int main()
{
    R5900Decoder decoder;
    CodeGenerator generator({}, {});
    std::puts("// Generated by e54d_lwu_snippet_gen from decoded instructions.");
    std::puts("#pragma once");
    const struct { const char *name; uint32_t opcode; uint32_t rt; } entries[] = {
        {"LWU", OPCODE_LWU, 5}, {"LW", OPCODE_LW, 5},
        {"LBU", OPCODE_LBU, 5}, {"LHU", OPCODE_LHU, 5},
        {"LWU_ZERO", OPCODE_LWU, 0},
    };
    for (const auto &entry : entries)
    {
        // base=$a0 (4), offset=4, destination=$a1 (5) or $zero.
        const uint32_t word = (entry.opcode << 26) | (4u << 21) | (entry.rt << 16) | 4u;
        const Instruction inst = decoder.decodeInstruction(0x100000u, word);
        const auto code = generator.translateInstruction(inst);
        std::printf("// 0x%08x: %s\n", word, entry.name);
        std::printf("static inline void E54D_%s(R5900Context *ctx, uint8_t *rdram, PS2Runtime *runtime = nullptr)\n"
                    "{ (void)runtime; %s }\n", entry.name, code.c_str());
    }
}
